dist: trusty
language: go
go:
- 1.12
services:
- postgresql
addons:
  postgresql: '11.2'
go_import_path: github.com/makerdao/vulcanizedb
before_install:
- make installtools
- bash ./scripts/install-postgres-11.sh
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update && sudo apt-get install yarn
script:
- env GO111MODULE=on make test
- env GO111MODULE=on make integrationtest
notifications:
  email: false
env:
  matrix:
  - secure: yOHm+9/BOuOMuWYx20pLcfaD3//meUMyFcUEpwjKYE7ajzZM5ms1Hpn998BnXObunxPLmcVYYumI8K9HoT6KTCZMI+XB11WyWoy+7dRRrPgtFJt7dWdscNmtVVIy6Ka+QNQ6I8ER2KCnjbA8tSSnVxtctT/MT1TakKobFty5McbISw9ndXwQMRhKbl/AfK2GQ+gVyf9YdDBrw6/uXK8+2NM68csK+bUCRbh6F8YxQr7svqcaixPfQhtxOuIzXYcWiI22RkZFofSm9k+thEjAu/eTuoJM+H9ONIDH1xCOnLyXXr49y2QT5v2GBqbuemAi8Ew7yVQ0FUyCTetzIg7mnIzh9ZWxcUbBvqt+x63gWTmuwWQKnJ/5UwjN6kSp3vNuzhXOBP1K8MLYwFVx+9jfmus+WdFhHXR1A/dIAIT1QeSpsYIJXMrSeOV+86njOtvigwAXKO48+iP9AssiKa7oRuruZ3pYlFXhS/UWdEbvocq6gr/FwF6n2buhqh8vdfgf4zegHQEjRKpeIUBOiFEnpBNIczCG8770/07Ya0zme0M6HL/DWKKoI6DMFi+DxnIA6ZEN7dqP4PZrgvF7QjkpLeXyx3LDx91I3Mm+D2InIPy0pyYpMBDbMOZBnaVDO2X1jpyIaT1ZAhpeUNos4PLJXwqnCsWjwwIhnHDgvZAdfao=
